#spring.mvc.view.prefix=/WEB-INF/jsp/
#spring.mvc.view.suffix=.jsp
#server.port=8085
#
#spring.datasource.hikari.connectionTimeout=20000
#spring.datasource.hikari.maximumPoolSize=5
#spring.jpa.generate-ddl=true
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:postgresql://localhost:5432/nclt_1507
##spring.datasource.url=jdbc:postgresql://10.247.159.164:5432/resdb?currentSchema=icesres
#spring.datasource.username=postgres
#spring.datasource.password=nic
#spring.jpa.hibernate.ddl-auto=update
#spring.application.name=employee
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

server:
  port: 8085
  
  
spring:
 application:
  name: employee mvc:    view:      prefix: /WEB-INF/jsp/
      suffix: .jsp datasource:    hikari:     connection-timeout: 20000
     maximum-pool-size: 5    url: jdbc:postgresql://localhost:5432/nclt_1507
    username: postgres
    password: nic jpa:    generate-ddl: true    show-sql: true
    hibernate:      ddl-auto: update
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/